sudo: false
language: java

dist:
  - trusty

before_script:
  - if [[ "x$JDK" == *'x9'* ]]; then export MAVEN_SKIP_RC=true; fi

script:
  - export JDK8_HOME=$(jdk_switcher home oraclejdk8)
#  - export JDK9_HOME=/usr/lib/jvm/java-9-oracle
#  - test -d "${JDK9_HOME}" || export JDK9_HOME=$(jdk_switcher home oraclejdk8)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
#    - jdk: oraclejdk9
#      env:
#        - JDK=9

install: /bin/true

script:
  - ./gradlew build -x test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: bintray
  file: descriptor.json
  user:
    secure: Tos9FGRPVqVjhqlZt7G4FA56MamwewOPerp3QAPZI0bpiqSQbx08HV+UQ2E6k6VYzWAoNSisVQudhqzxbk+acPDMJXpUWezTC7WWJCikvGUp9DzuuxZcoRGJ7DpLLxoHexlUOImA76vM7wIuy9NoyYPxFNnpGDjrxzpA8Z1Pyw40+oN5v3KgDO19p2eHVfCefg+/CgyB217LW+Tr/wq6+jEKnchA7xat5im5Mqc6wTVm+NZtyjgnB9QCl3tCvxB88FApjdh40wutVYlRmOgE5WS3tzizBNOa/Xv7v+1lyh9SgxD8Vk9MexsUpM7FbYXrzjGD+e7jpLSJhO4o7WtTuLiQadwFBsuAS78FWPqMRiYhX6b+tOs8CYmh2RYf/4m2+o644LnUP9Z26iyQni4OpzDP3VFHmGOOsxMlIQHj1GE3rA7U01VbfeoNAlQViTOklAv80VK6xc0pmkJvOC5O5NvRnWh67HhVt/hKj3I80bAW03pD+ZAoBGX5Mfm1C9Yf4tbzbM7Z8viARHs5tb/TKsXLkivkW6GgmnSzlDqCKl5+PqqbJXTmuRnn87Iyr/1eZ5OIgX342izPl3IK7hhAqimL59BSjmxZ35JD7OcCV1k8n6vnMx2Gvkx3Ocm5VWqAlHZ5J9BnjFSBEaaLLuj5R/AjvJ+1FVsi7zG4js5/WOQ=
  key:
    secure: YQwYGJUZnZU/6jgT7aJIW1+Ne5NWI4nc6WPOI5r+7BTz0EAEX+KBtEyGWXuPimKP4jCSKTM+Cu8K+7VLcSQZ6ZEfK5FH6zvY/BYvIUSKwTwy77uStT8mmf/F+ehX6aOrQCHoVNaY8X2emLk7DqDu4ZlKWciAdJAUxQoIgTiRkwnhXOdTcMnSAW9PGvo7w08orCz0fseL/Qn1g9r2oeoyU8jzYWQgtLWCUjf3V1bPpb7+YiaEpp1bD5tz3UZB+WxskFFkMyweVeDaLNUua/96YyXvs/03CRuoeKl+reuZcQZD2ExLzLPfGL2rdP3pY8taMM9sfFO6s/tzx0gtb0l2wVbEofODWotQxhCG5FlqcHWm/TvFv6d0f+DFc/Pi9J5439GR9gwDZOyanpFQS0tSBt3WEszT8TPLdWwttkr8IDNBww0jbuMIyXzv1zLpgqmGAt8V92UInIVt8Fi48x74MhJxdEi2e+cgxFvKpCeXuHw9Xq3sJwHeo4w7OclvHTboNqxyPUcqWAVL90rzv6hP63iHVPbJPrizEYJLHWnd7sKVvIbZIefbhyznQDIczq9IsTIYpmOAY08CR4AKPlnM/nR7GzQrfx6P5AN4GL9VpEHPGhc7UszsbyMcJ4zXlXanm2AoLgU+JmDoosrtkaO0MzoV6sm5sAuYmsUnIoVb8gk=
