package org.scriptonbasestar.tool.crypto.symmetry;

import lombok.Getter;

/**
 *
 * DIGEST ALGORITHMS:   [MD2, MD5, SHA, SHA-256, SHA-384, SHA-512]
 * PBE ALGORITHMS:      [PBEWITHMD5ANDDES, PBEWITHMD5ANDTRIPLEDES, PBEWITHSHA1ANDDESEDE, PBEWITHSHA1ANDRC2_40]
 *
 * https://sourceforge.net/p/jasypt/bugs/32/
 *
 * PBEWITHHMACSHA1ANDAES_128
 * PBEWITHHMACSHA1ANDAES_256
 * PBEWITHHMACSHA224ANDAES_128
 * PBEWITHHMACSHA224ANDAES_256
 * PBEWITHHMACSHA256ANDAES_128
 * PBEWITHHMACSHA256ANDAES_256
 * PBEWITHHMACSHA384ANDAES_128
 * PBEWITHHMACSHA384ANDAES_256
 * PBEWITHHMACSHA512ANDAES_128
 * PBEWITHHMACSHA512ANDAES_256
 *
 * A. Without JCE jars installed:
 * PBEWITHHMACSHA1ANDAES_128       NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA1ANDAES_256       NOT_POSSIBLE
 * PBEWITHHMACSHA224ANDAES_128     NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA224ANDAES_256     NOT_POSSIBLE
 * PBEWITHHMACSHA256ANDAES_128     NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA256ANDAES_256     NOT_POSSIBLE
 * PBEWITHHMACSHA384ANDAES_128     NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA384ANDAES_256     NOT_POSSIBLE
 * PBEWITHHMACSHA512ANDAES_128     NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA512ANDAES_256     NOT_POSSIBLE
 * PBEWITHMD5ANDDES                OK
 * PBEWITHMD5ANDTRIPLEDES          NOT_POSSIBLE
 * PBEWITHSHA1ANDDESEDE            OK
 * PBEWITHSHA1ANDRC2_128           OK
 * PBEWITHSHA1ANDRC2_40            OK
 * PBEWITHSHA1ANDRC4_128           OK
 * PBEWITHSHA1ANDRC4_40            OK
 *
 * B. With JCE jars installed:
 * PBEWITHHMACSHA1ANDAES_128 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA1ANDAES_256 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA224ANDAES_128 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA224ANDAES_256 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA256ANDAES_128 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA256ANDAES_256 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA384ANDAES_128 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA384ANDAES_256 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA512ANDAES_128 NOT_POSSIBLE_DECRYPT
 * PBEWITHHMACSHA512ANDAES_256 NOT_POSSIBLE_DECRYPT
 * PBEWITHMD5ANDDES OK
 * PBEWITHMD5ANDTRIPLEDES OK
 * PBEWITHSHA1ANDDESEDE OK
 * PBEWITHSHA1ANDRC2_128 OK
 * PBEWITHSHA1ANDRC2_40 OK
 * PBEWITHSHA1ANDRC4_128 OK
 * PBEWITHSHA1ANDRC4_40 OK
 */
public enum SymmetryAlgorithm {
//	AES(""),
//	Aria("Aria"),
	DES("PBEWITHMD5ANDDES"),
	TripleDES("PBEWITHMD5ANDTRIPLEDES"),
	DESEDE("PBEWITHSHA1ANDDESEDE"),
	/**
	 * https://en.wikipedia.org/wiki/RC2
	 */
	RC2_40("PBEWITHSHA1ANDRC2_40"),
	RC2_128("PBEWITHSHA1ANDRC2_128"),
	/**
	 * https://en.wikipedia.org/wiki/RC4
	 */
	RC4_40("PBEWITHSHA1ANDRC4_40"),
	RC4_128("PBEWITHSHA1ANDRC4_128");

	SymmetryAlgorithm(final String val) {
		this.val = val;
	}

	@Getter
	private final String val;

}
